const $=s=>document.querySelector(s);
const api=async(url,opt={})=>{const r=await fetch(url,{credentials:"include",...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||"Something went wrong");return d};
const toast=(m)=>{const t=$("#toast");t.className="toast";t.textContent=m;clearTimeout(window.__t);window.__t=setTimeout(()=>t.className="",2600)};
function showLanding(){$("#landing").classList.remove("hidden");$("#auth").classList.add("hidden");$("#dashboard").classList.add("hidden")}
function showAuth(mode){$("#landing").classList.add("hidden");$("#auth").classList.remove("hidden");renderAuth(mode)}
function renderAuth(mode){
$("#authContent").innerHTML=mode==="login"?`
<form class="auth-form" onsubmit="login(event)"><h1>Welcome back 👋</h1><p>Continue your campus journey.</p><label>Username or email</label><input id="identifier" required><label>Password</label><input id="password" type="password" required><button class="primary">Login</button><div class="switch">New here? <span class="link" onclick="renderAuth('register')">Create an account</span></div></form>`:
`<form class="auth-form" onsubmit="register(event)"><h1>Join Aditya Connect</h1><p>Create your student community profile.</p><label>Full name</label><input id="full_name" required><label>Username</label><input id="username" pattern="[A-Za-z0-9_]{3,30}" required><label>College email</label><input id="email" type="email" required><label>Password</label><input id="password" type="password" minlength="8" required><label>Department</label><select id="department"><option>MCA</option><option>BCA</option><option>B.Tech</option><option>MBA</option><option>B.Com</option><option>M.Tech</option><option>Other</option></select><label>Year</label><select id="year"><option>1st Year</option><option>2nd Year</option><option>3rd Year</option><option>Final Year</option></select><button class="primary">Create account</button><div class="switch">Already a member? <span class="link" onclick="renderAuth('login')">Login</span></div></form>`;
}
async function login(e){e.preventDefault();try{await api("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({identifier:$("#identifier").value,password:$("#password").value})});toast("Welcome back!");loadDashboard()}catch(x){toast(x.message)}}
async function register(e){e.preventDefault();try{await api("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({full_name:$("#full_name").value,username:$("#username").value,email:$("#email").value,password:$("#password").value,department:$("#department").value,year:$("#year").value,section:"A"})});toast("Account created. Please log in.");renderAuth("login")}catch(x){toast(x.message)}}
async function loadDashboard(){try{const me=await api("/api/auth/me");renderDashboard(me);await loadFeed()}catch{showLanding()}}
function renderDashboard(me){
$("#landing").classList.add("hidden");$("#auth").classList.add("hidden");const d=$("#dashboard");d.classList.remove("hidden");
d.innerHTML=`<div class="dashboard"><header class="dash-nav"><div class="brand"><span class="brand-mark">A</span> Aditya <b>Connect</b></div><div><button class="ghost" onclick="openSearch()">🔍 Search</button><button class="ghost" onclick="toggleTheme()">◐</button><button class="ghost" onclick="logout()">Logout</button></div></header><div class="dash-layout"><aside class="sidebar"><button class="navitem active" onclick="loadFeed()">🏠 <span class="navtext">Home</span></button><button class="navitem" onclick="loadExplore()">✨ <span class="navtext">Explore</span></button><button class="navitem" onclick="loadReels()">🎬 <span class="navtext">Reels</span></button><button class="navitem" onclick="loadNotifications()">🔔 <span class="navtext">Notifications</span></button><button class="navitem" onclick="loadCommunities()">👥 <span class="navtext">Communities</span></button><button class="navitem" onclick="loadEvents()">📅 <span class="navtext">Events</span></button><button class="navitem" onclick="loadProfile('${me.username}')">👤 <span class="navtext">Profile</span></button>${me.role==="admin"?`<button class="navitem" onclick="loadAdmin()">🛡️ <span class="navtext">Admin</span></button>`:""}</aside><main id="main"></main><aside class="rightbar"><div class="side-card"><h3>Trending</h3><div class="trend">#MCA <small class="muted"> · student life</small></div><div class="trend">#Coding <small class="muted"> · 128 posts</small></div><div class="trend">#CampusLife <small class="muted"> · 96 posts</small></div><div class="trend">#Hackathon <small class="muted"> · 71 posts</small></div></div><div class="side-card"><h3>Student tip</h3><p class="muted">Share projects, achievements and campus moments. Keep the community respectful.</p></div></aside></div></div>`;
}
async function loadFeed(){
$("#main").innerHTML=`<h1 class="feed-title">Good to see you 👋</h1><div class="composer"><div class="composer-row"><div class="avatar">+</div><textarea id="caption" rows="2" placeholder="Share something with Aditya students..."></textarea></div><div class="composer-actions"><label class="file-label">📎 Add photo/video <input id="media" type="file" accept="image/*,video/*" hidden></label><button class="primary" onclick="createPost()">Post</button></div></div><div id="feed"><div class="empty">Loading your campus feed...</div></div>`;
try{const posts=await api("/api/posts");const feed=$("#feed");feed.innerHTML=posts.length?posts.map(postHTML).join(""):`<div class="empty">No posts yet. Be the first to share something!</div>`}catch(e){toast(e.message)}
}
function postHTML(p){return `<article class="post-card"><div class="post-head"><div class="avatar">${esc(p.author.name[0])}</div><div class="post-meta"><b>${esc(p.author.name)}</b><small>${esc(p.author.department)} · @${esc(p.author.username)} · ${time(p.created_at)}</small></div></div>${p.caption?`<div class="post-caption">${esc(p.caption)}</div>`:""}${p.media_url?(p.media_type==="image"?`<img class="post-media" src="${p.media_url}" loading="lazy">`:`<video class="post-media" src="${p.media_url}" controls preload="metadata"></video>`):""}<div class="post-actions"><button class="action ${p.liked?"liked":""}" onclick="likePost(${p.id},this)">❤️ <span>${p.likes}</span></button><button class="action" onclick="comments(${p.id})">💬 ${p.comments}</button><button class="action" onclick="sharePost()">↗ Share</button><button class="action">🔖 Save</button></div></article>`}
async function createPost(){const fd=new FormData();fd.append("caption",$("#caption").value);const f=$("#media").files[0];if(f)fd.append("media",f);try{await api("/api/posts",{method:"POST",body:fd});toast("Posted!");loadFeed()}catch(e){toast(e.message)}}
async function likePost(id,el){try{const d=await api(`/api/posts/${id}/like`,{method:"POST"});el.classList.toggle("liked",d.action==="liked");el.querySelector("span").textContent=d.likes}catch(e){toast(e.message)}}
async function comments(id){try{const rows=await api(`/api/posts/${id}/comments`);showModal(`<h2>Comments</h2>${rows.map(c=>`<div class="user-result"><div class="avatar">${esc(c.name[0])}</div><div><b>${esc(c.name)}</b><div class="muted">${esc(c.body)}</div></div></div>`).join("")||'<p class="muted">No comments yet.</p>'}<form onsubmit="addComment(event,${id})"><input id="commentBody" placeholder="Write a comment..." required><button class="primary" style="margin-top:10px">Comment</button></form>`)}catch(e){toast(e.message)}}
async function addComment(e,id){e.preventDefault();try{const fd=new FormData();fd.append("body",$("#commentBody").value);await api(`/api/posts/${id}/comments`,{method:"POST",body:fd});toast("Comment added");closeModal();comments(id)}catch(x){toast(x.message)}}
function sharePost(){navigator.clipboard?.writeText(location.href);toast("Link copied")}
async function loadReels(){const rs=await api("/api/reels");$("#main").innerHTML=`<div class="reels-shell">${rs.length?rs.map(r=>`<article class="reel"><video src="${r.video_url}" muted loop playsinline preload="metadata"></video><div class="reel-info"><b>@${esc(r.author.username)}</b><p>${esc(r.caption)}</p><small>${r.views} views</small></div><div class="reel-actions"><button onclick="likeReel(${r.id},this)">❤️<br><small>${r.likes}</small></button><button onclick="commentsReel(${r.id})">💬</button><button onclick="sharePost()">↗</button></div></article>`).join(""):`<div class="empty">No reels yet. Upload one through the Create Reel option below.</div>`}</div><div style="position:fixed;right:25px;bottom:25px;z-index:10"><button class="primary" onclick="openReelUpload()">＋ Reel</button></div>`;const obs=new IntersectionObserver(entries=>entries.forEach(e=>{const v=e.target;if(e.isIntersecting){v.play().catch(()=>{});const id=v.closest(".reel")?.querySelector("video")?.src;const reel=rs.find(x=>id&&id.endsWith(x.video_url));if(reel)api(`/api/reels/${reel.id}/view`,{method:"POST"}).catch(()=>{})}else v.pause()}),{threshold:.7});document.querySelectorAll(".reel video").forEach(v=>obs.observe(v))}
async function likeReel(id,el){try{const d=await api(`/api/reels/${id}/like`,{method:"POST"});el.innerHTML=`❤️<br><small>${d.likes}</small>`}catch(e){toast(e.message)}}
function openReelUpload(){showModal(`<h2>Create a Reel</h2><p class="muted">Use a short vertical MP4/WebM/MOV video.</p><label>Caption</label><textarea id="reelCaption"></textarea><label>Video</label><input id="reelVideo" type="file" accept="video/mp4,video/webm,video/quicktime"><button class="primary" style="margin-top:18px" onclick="uploadReel()">Upload Reel</button>`)}
async function uploadReel(){const f=$("#reelVideo").files[0];if(!f)return toast("Select a video");const fd=new FormData();fd.append("caption",$("#reelCaption").value);fd.append("video",f);try{await api("/api/reels",{method:"POST",body:fd});closeModal();toast("Reel uploaded");loadReels()}catch(e){toast(e.message)}}
async function loadProfile(username){const p=await api(`/api/users/${username}`);$("#main").innerHTML=`<div class="side-card"><div style="display:flex;gap:20px;align-items:center"><div class="avatar" style="width:80px;height:80px;font-size:28px">${esc(p.name[0])}</div><div><h1 style="margin:0">${esc(p.name)}</h1><div class="muted">@${esc(p.username)} · ${esc(p.department)} · ${esc(p.year)}</div><p>${esc(p.bio)}</p><button class="primary" onclick="toggleFollow('${p.username}')">${p.followed?"Following":"Follow"}</button></div></div><hr style="border-color:var(--line);margin:24px 0"><div style="display:flex;gap:30px"><b>${p.posts}<small class="muted"> Posts</small></b><b>${p.reels}<small class="muted"> Reels</small></b><b>${p.followers}<small class="muted"> Followers</small></b><b>${p.following}<small class="muted"> Following</small></b></div></div>`}
async function toggleFollow(u){await api(`/api/users/${u}/follow`,{method:"POST"});loadProfile(u)}
async function loadNotifications(){const n=await api("/api/notifications");await api("/api/notifications/read",{method:"POST"});$("#main").innerHTML=`<h1 class="feed-title">Notifications</h1><div class="side-card">${n.map(x=>`<div class="trend">🔔 ${esc(x.message)}<small class="muted"> · ${time(x.created_at)}</small></div>`).join("")||"<p class='muted'>You're all caught up.</p>"}</div>`}
async function loadCommunities(){const c=await api("/api/communities");$("#main").innerHTML=`<h1 class="feed-title">Communities</h1><div class="feature-grid" style="padding:0;grid-template-columns:repeat(2,1fr)">${c.map(x=>`<article><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><button class="ghost">Join community</button></article>`).join("")}</div>`}
async function loadEvents(){const e=await api("/api/events");$("#main").innerHTML=`<h1 class="feed-title">Campus Events</h1>${e.map(x=>`<div class="side-card"><h2>${esc(x.title)}</h2><div class="muted">📅 ${esc(x.date)} · 📍 ${esc(x.location)}</div><p>${esc(x.description)}</p><button class="primary">I'm interested</button></div>`).join("")}`}
async function loadExplore(){const users=await api("/api/users/search?q=a");$("#main").innerHTML=`<h1 class="feed-title">Explore</h1><div class="side-card"><h3>Student creators</h3>${users.map(u=>`<div class="user-result" onclick="loadProfile('${esc(u.username)}')"><div class="avatar">${esc(u.name[0])}</div><div><b>${esc(u.name)}</b><div class="muted">@${esc(u.username)} · ${esc(u.department)}</div></div></div>`).join("")}</div><div class="side-card"><h3>Trending hashtags</h3><div class="trend">#MCA</div><div class="trend">#Coding</div><div class="trend">#CampusLife</div><div class="trend">#Hackathon</div></div>`}
async function openSearch(){showModal(`<h2>Search students</h2><input id="searchInput" placeholder="Search by name or username..." oninput="doSearch()"><div id="searchResults" class="search-results"></div>`)}
let searchTimer;function doSearch(){clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{const q=$("#searchInput").value;if(!q)return;const r=await api(`/api/users/search?q=${encodeURIComponent(q)}`);$("#searchResults").innerHTML=r.map(u=>`<div class="user-result" onclick="closeModal();loadProfile('${esc(u.username)}')"><div class="avatar">${esc(u.name[0])}</div><div><b>${esc(u.name)}</b><div class="muted">@${esc(u.username)} · ${esc(u.department)}</div></div></div>`).join("")||"<p class='muted'>No students found.</p>"},250)}
async function loadAdmin(){const s=await api("/api/admin/stats");const u=await api("/api/admin/users");$("#main").innerHTML=`<h1 class="feed-title">Admin Dashboard</h1><div class="admin-grid">${Object.entries(s).map(([k,v])=>`<div class="stat">${k}<b>${v}</b></div>`).join("")}</div><div class="side-card" style="margin-top:18px"><h3>Users</h3>${u.map(x=>`<div class="trend"><b>${esc(x.name)}</b> <span class="muted">@${esc(x.username)}</span><button class="ghost" style="float:right" onclick="disableUser(${x.id})">${x.disabled?"Enable":"Disable"}</button></div>`).join("")}</div>`}
async function disableUser(id){await api(`/api/admin/users/${id}/disable`,{method:"PATCH"});toast("User status updated");loadAdmin()}
async function logout(){await api("/api/auth/logout",{method:"POST"});showLanding();toast("Logged out")}
function showModal(html){let m=document.createElement("div");m.id="modal";m.className="modal";m.innerHTML=`<div class="modal-card"><button class="close" onclick="closeModal()">×</button>${html}</div>`;document.body.appendChild(m)}
function closeModal(){$("#modal")?.remove()}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function time(x){return new Date(x).toLocaleString([], {month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}
function toggleTheme(){document.body.classList.toggle("light")}
window.addEventListener("DOMContentLoaded",async()=>{try{const me=await api("/api/auth/me");renderDashboard(me);loadFeed()}catch{}});
